runtime: nodejs12

instance_class: F2

env_variables:
    DB_PORT:  $DB_PORT
    DB_HOST:  $DB_HOST
    DB_NAME: $DB_NAME
    DB_USER: $DB_USER
    DB_PASSWORD: $DB_PASSWORD
    GOOGLE_API_KEY: $GOOGLE_API_KEY
    NODE_ENV: production
    HOST: 0.0.0.0
    SECRET: $SECRET

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto